<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>NetCoreBackend.NArchitecture.$(AssemblyName)</RootNamespace>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageId>NetCoreBackend.NArchitecture.$(AssemblyName)</PackageId>
    <Version>1.0.1</Version>
    <Title>NetCoreBackend NArchitecture $(AssemblyName)</Title>
    <Description>Provides utilities for integrating security features with ASP.NET Web API projects,
      focusing on Swagger integration.</Description>
    <Product>NetCoreBackend NArchitecture</Product>
    <Authors>Caner Demirkol, Contributors</Authors>
    <Company></Company>
    <PackageTags>Clean Architecture, Union Architecture, Core, NArchitecture, Security,
      Authentication, Authorization, Swagger, Web API, Documentation, JWT, Two-Factor
      Authentication, OTP, Email Handling, Hashing, Encryption</PackageTags>
    <PackageIcon></PackageIcon>
    <RepositoryUrl></RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" />
  </ItemGroup>

</Project>