<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>NetCoreBackend.NArchitecture.$(AssemblyName)</RootNamespace>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageId>NetCoreBackend.NArchitecture.$(AssemblyName)</PackageId>
    <Version>2.0.0</Version>
    <Title>NetCoreBackend NArchitecture $(AssemblyName)</Title>
    <Description>Provide CQRS, MediatR, Pipelines, DTOs, and more for the Application Layer.</Description>
    <Product>NetCoreBackend NArchitecture</Product>
    <Authors>Caner Demirkol, Contributors</Authors>
    <Company></Company>
    <PackageTags>CQRS, MediatR, Clean Architecture, Union Architecture, Core, NArchitecture</PackageTags>
    <PackageIcon></PackageIcon>
    <RepositoryUrl></RepositoryUrl>
  </PropertyGroup>
  <ItemGroup>
	  <FrameworkReference Include="Microsoft.AspNetCore.App" />
	  <PackageReference Include="FluentValidation" />
	  <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
	  <PackageReference Include="MediatR" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Core.CrossCuttingConcerns.Logging.Abstraction\Core.CrossCuttingConcerns.Logging.Abstraction.csproj" />
    <ProjectReference Include="..\Core.CrossCuttingConcerns.Logging\Core.CrossCuttingConcerns.Logging.csproj" />
    <ProjectReference Include="..\Core.CrossCuttingConcerns.Exception\Core.CrossCuttingConcerns.Exception.csproj" />
    <ProjectReference Include="..\Core.Security\Core.Security.csproj" />
    <ProjectReference Include="..\Core.MultiTenancy\Core.MultiTenancy.csproj" />
  </ItemGroup>
</Project>