<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
    <PackageReference Include="Moq" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core.Application\Core.Application.csproj" />
    <ProjectReference Include="..\Core.Persistence\Core.Persistence.csproj" />
    <ProjectReference Include="..\Core.MultiTenancy\Core.MultiTenancy.csproj" />
    <ProjectReference Include="..\Core.Security\Core.Security.csproj" />
    <ProjectReference Include="..\Core.Outbox\Core.Outbox.csproj" />
  </ItemGroup>

</Project>