<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
	<TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>NetCoreBackend.NArchitecture.$(AssemblyName)</RootNamespace>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageId>NetCoreBackend.NArchitecture.$(AssemblyName)</PackageId>
    <Version>1.0.1</Version>
    <Title>NetCoreBackend NArchitecture $(AssemblyName)</Title>
    <Description>Provide exception handling components specifically tailored for ASP.NET Web API
      projects.</Description>
    <Product>NetCoreBackend NArchitecture</Product>
    <Authors>Caner Demirkol, Contributors</Authors>
    <Company></Company>
    <PackageTags>Clean Architecture, Union Architecture, Core, NArchitecture, Web API, Exception
      Handling, Cross Cutting Concerns</PackageTags>
    <PackageIcon></PackageIcon>
    <RepositoryUrl></RepositoryUrl>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Newtonsoft.Json"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core.CrossCuttingConcerns.Logging.Abstraction\Core.CrossCuttingConcerns.Logging.Abstraction.csproj" />
    <ProjectReference Include="..\Core.CrossCuttingConcerns.Logging\Core.CrossCuttingConcerns.Logging.csproj" />
    <ProjectReference Include="..\Core.CrossCuttingConcerns.Exception\Core.CrossCuttingConcerns.Exception.csproj" />
  </ItemGroup>

</Project>